Accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
  path('register/', views.register, name="registration"),
  path('signin/', views.sign_in, name="signin"),
  path('changepassword/', views.change_password, name="changepassword"),
  path('logout/', views.sign_off, name="logout"),
  path('account/', views.my_account, name="my_account"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FlightRadar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OpenSkyProxy.urls')),
    path('', include('Accounts.urls')),
]

Accounts/models.py
from django.db import models

# Create your models here.

Accounts/forms.py
from django import forms
from django.contrib.auth.password_validation import MinimumLengthValidator, NumericPasswordValidator, UserAttributeSimilarityValidator


class RegisterForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=50, widget=forms.TextInput(attrs={'class':'input'}))
    last_name = forms.CharField(label='Last name', max_length=100, widget=forms.TextInput(attrs={'class':'input'}))
    username = forms.CharField(label='Username', max_length=100, widget=forms.TextInput(attrs={'class':'input'}))
    email = forms.EmailField(label='Email', max_length=100, widget=forms.EmailInput(attrs={'class':'input'}))
    #validators = [MinimumLengthValidator, NumericPasswordValidator, UserAttributeSimilarityValidator]
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'input'}), validators=[MinimumLengthValidator])

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, widget=forms.TextInput(attrs={'class':'input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'input'}))


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))


class UserDataForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=50, widget=forms.TextInput(attrs={'class':'input'}))
    last_name = forms.CharField(label='Last name', max_length=100, widget=forms.TextInput(attrs={'class':'input'}))
    username = forms.CharField(label='Username', max_length=100, widget=forms.TextInput(attrs={'class':'input'}))
    email = forms.EmailField(label='Email', max_length=100, widget=forms.EmailInput(attrs={'class':'input'}))
    account_type = forms.CharField(label='Account type', max_length=100, widget=forms.TextInput(attrs={'class': 'input'}))

Accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.middleware.csrf import get_token
from .forms import RegisterForm, LoginForm, ChangePasswordForm
from django.contrib.auth.hashers import check_password
from .validate import MinimumLengthValidator, NumberValidator, UppercaseValidator
from django.core.exceptions import ValidationError

#Registration
def register(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            response = redirect("/")
        else:
            form = RegisterForm()
            response = render(request, 'register.html', {'form': form})
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                result = {
                    'result': 'The registration has been unsuccessfull! A user with this username is already registered!'
                }
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                result = {
                    'result': 'The registration has been unsuccessfull! A user with this email is already registered!'
                }
            else:
                #Validate password
                validators = [MinimumLengthValidator, NumberValidator, UppercaseValidator]
                try:
                    for validator in validators:
                        validator().validate(form.cleaned_data['password'])
                except ValidationError as e:
                    result = {
                        'result': str(e)[2:-3]
                    }
                    return render(request, 'register.html', {'form': form, 'result': result})

                #Create user
                user = User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password'])
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
                result = {
                    'success': 'The registration has been successfull!'
                }
        else:
            result = {
                'result': 'Form is invalid!'
            }
        response = render(request, 'register.html', {'form': form, 'result': result})
    else:
        result = {
            'result': 'Incorrect type of request'
        }
        response = render(request, 'result_unauth.html', {'result': result})
    response.set_cookie("csrftoken", get_token(request))
    return response


#Sign in
def sign_in(request):
    if request.user.is_authenticated:
        response = redirect("/")
    else:
        if request.method == 'GET':
            form = LoginForm()
            response = render(request, 'signin.html', {'form': form})
        elif request.method == 'POST':
            form = LoginForm(request.POST)
            print(form)
            if form.is_valid():
                user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
                if user is not None:
                    login(request, user)
                    response = redirect('/')
                else:
                    result = {
                        'failure': 'The username or password is incorrect!'
                    }
                    response = render(request, 'signin.html', {'form': form, 'result': result})
            else:
                result = {
                    'failure': 'Form is invalid!'
                }
                response = render(request, 'signin.html', {'form': form, 'result': result})
        else:
            result = {
                'result': 'Incorrect type of request'
            }
            response = render(request, 'result_unauth.html', {'result': result})
    response.set_cookie("csrftoken", get_token(request))
    return response


def change_password(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            form = ChangePasswordForm()
            user = request.user
            account_type = "Admin" if user.is_superuser else "Standard user"
            data = {
                'account_type': account_type,
            }
            response = render(request, 'change_password.html', {'form': form, 'data': data})
        elif request.method == 'POST':
            form = ChangePasswordForm(request.POST)
            user = request.user
            account_type = "Admin" if user.is_superuser else "Standard user"
            data = {
                'account_type': account_type,
            }
            if form.is_valid():
                user = User.objects.get(username=request.user.username)
                current_password = user.password
                entered_password = form.cleaned_data['old_password']
                if user.is_authenticated and check_password(entered_password, current_password):
                    # Validate password
                    validators = [MinimumLengthValidator, NumberValidator, UppercaseValidator]
                    try:
                        for validator in validators:
                            validator().validate(form.cleaned_data['new_password'])
                    except ValidationError as e:
                        result = {
                            'failure': str(e)[2:-3]
                        }
                        return render(request, 'change_password.html', {'form': form, 'result': result, 'data':data})

                    #Change password
                    user.set_password(form.cleaned_data['new_password'])
                    user.save()
                    result = {
                        'success': 'Your password has been changed successfully!'
                    }
                else:
                    result = {
                        'failure': 'The data entered is incorrect!'
                    }
            else:
                result = {
                    'failure': "Form is invalid!"
                }
            response = render(request, 'change_password.html', {'form': form, 'result': result, 'data':data})
        else:
            result = {
                'result': 'Incorrect type of request'
            }
            response = render(request, 'result_auth.html', {'result': result})
    else:
        response = redirect("/")
    response.set_cookie("csrftoken", get_token(request))
    return response


def sign_off(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            logout(request)
            response = redirect("/")
        else:
            result = {
                'result': 'Incorrect type of request'
            }
            response = render(request, 'result_auth.html', {'result': result})
    else:
        response = redirect("/")
    response.set_cookie("csrftoken", get_token(request))
    return response


def my_account(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            user = request.user
            account_type = "Admin" if user.is_superuser else "Standard user"
            data = {
                'first_name': user.first_name,
                'last_name': user.last_name,
                'username': user.username,
                'email': user.email,
                'account_type': account_type,
            }
            response = render(request, 'my_account.html', {'data': data})
        else:
            result = {
                'result': 'Incorrect type of request'
            }
            response = render(request, 'result.html', {'result': result})
    else:
        result = {
            'result': 'You are not authenticated!',
        }
        response = render(request, 'result_unauth.html', {'result': result})
    response.set_cookie("csrftoken", get_token(request))
    return response

Accounts/templates/base_unauth.html
<!DOCTYPE html>
<html>
	<head>
		
		<!-- Jquery ref -->
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		
		<!-- Leaflet references -->
		<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
		integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
		crossorigin=""/>	
		<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
		integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
		crossorigin=""></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-realtime/2.2.0/leaflet-realtime.min.js" type="text/javascript"></script>
		
		<!-- Bootstrap references -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
		
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!-- JS Cookie -->		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
		
		{% load  static %}
		<!-- Internal references -->
		<link rel="stylesheet" href="{% static 'css/styles.css' %}">
		<script type="text/javascript" src="{% static 'js/unauth-script.js' %}"></script>
		<script type="text/javascript">
			PLANE_IMG = "{% static 'images/plane.png' %}";
		</script>
		
		{% block include %} {% endblock %}
		
		<!-- Disabling link underscores -->
		<STYLE>A {text-decoration: none;} </STYLE>
	</head>	
	
	<body class="bg-black container-fluid">
		<br>
		<div class="row justify-content-center">
			<div id="menu" class="col-xl-3 col-sm-12">
				<a href='/register/' id="register" class="menu-button text-white border border-white bg-black text-center">SIGN UP</a>
				<a href='/signin/' id="login" class="menu-button text-white border border-white bg-black text-center">SIGN IN</a>
				<a href='/' id="monitor" class="menu-button text-white border border-white bg-black text-center">WATCH PLANES</a>
			</div>
			
			{% block content %}	{% endblock %}
			
		</div>
		
	</body>	
</html>

Accounts/templates/change_password.html
{% extends "base_auth.html" %}

{% block content %}	
	<form id="register_form" class="col-xl-9 col-sm-12 text-white border border-white" action="" method="post"> 
		{% csrf_token %}
		<div class="center-block container-fluid form_data">
		
			<div class="row">
				<h2 class="border border-white bg-black">CHANGE PASSWORD</h2>
			</div>

			<div class="row">
				<label class="label" for="id_old_password">Current password:</label>
				{{form.old_password}}
			</div><br>
			
			<div class="row">
				<label class="label" for="id_new_password">New password:</label>
				{{form.new_password}}
			</div><br>
			
				<p class="text-danger text-center">{{result.failure}}</p>
				<p class="text-success text-center">{{result.success}}</p>
			
			<div class="row">
				<input id="submit_change_password" class="text-white border border-white bg-black submit_button" type="submit" value="Submit">
			</div>
		</div>
	</form>
{% endblock %}

Accounts/templates/my_account.html
{% extends "base_auth.html" %}

{% block content %}	
	<div id="my_account" class="col-xl-9 col-sm-12 text-white border border-white"> 
		{% csrf_token %}
		<div class="center-block container-fluid form_data">
		
			<div class="row">
				<h2 class="border border-white bg-black">MY ACCOUNT INFO</h2>
			</div>
			
			{% if data.first_name %}
			<div class="row">
				<label class="label" for="id_first_name">First name:</label>
				{{data.first_name}}
			</div><br>
			{% endif %}

			{% if data.last_name %}
			<div class="row">
				<label class="label" for="id_last_name">Last name:</label>
				{{data.last_name}}
			</div><br>
			{% endif %}
			
			
			<div class="row">
				<label class="label" for="id_username">Username:</label>
				{{data.username}}
			</div><br>

			{% if data.email %}
			<div class="row">
				<label class="label" for="id_email">Email:</label>
				{{data.email}}
			</div><br>
			{% endif %}

			<div class="row">
				<label class="label" for="id_account_type">Account type:</label>
				{{data.account_type}}
			</div>
			
			{% if data.my_flights %}
			<div class="row">
				<label class="label" for="id_my_flights">My flights:</label>
				{{data.flights}}
			</div>
			{% endif %}
		</div>
	</div>
{% endblock %}

Accounts/templates/register.html
{% extends "base_unauth.html" %}

<!-- {% block include %}  -->
<!-- {% load  static %} -->
<!-- <script type="text/javascript" src="{% static 'js/register_script.js' %}"></script> -->
<!-- {% endblock %} -->

{% block content %}	
	<form id="register_form" class="col-xl-9 col-sm-12 text-white border border-white" action="" method="post"> 
		{% csrf_token %}
		<div class="center-block container-fluid form_data">
		
			<div class="row">
				<h2 class="border border-white bg-black">REGISTRATION FORM</h2>
			</div>
			
			<div class="row">
				<label class="label" for="id_first_name">First name:</label>
				{{form.first_name}}
			</div><br>

			<div class="row">
				<label class="label" for="id_last_name">Last name:</label>
				{{form.last_name}}
			</div><br>
			
			<div class="row">
				<label class="label" for="id_username">Username:</label>
				{{form.username}}
			</div><br>

			<div class="row">
				<label class="label" for="id_email">Email:</label>
				{{form.email}}
			</div><br>

			<div class="row">
				<label class="label" for="id_password">Password:</label>
				{{form.password}}
			</div><br>
			
			<div class="row">
				<p class="text-danger text-center">{{result.result}}</p>
				<p class="text-success text-center">{{result.success}}</p>
			</div>
			
			<div class="row">
				<input id="submit_registration" class="text-white border border-white bg-black submit_button" type="submit" value="Submit">
			</div>
		</div>
	</form>
{% endblock %}

Accounts/templates/result_auth.html
{% extends "base_auth.html" %}

{% block content %}	

<div id="result" class="col-xl-9 text-white border border-white align-items-center justify-content-center">
	<p id="result_text" class="bold"> {{result.result}}</p>
</div>
			
{% endblock %}

Accounts/templates/result_unauth.html
{% extends "base_unauth.html" %}

{% block content %}	

<div id="result" class="col-xl-9 text-white border border-white align-items-center justify-content-center">
	<p id="result_text" class="bold"> {{result.result}}</p>
</div>
			
{% endblock %}

Accounts/templates/signin.html
{% extends "base_unauth.html" %}

{% block content %}	
	<form id="login_form" class="col-xl-9 col-sm-12 text-white border border-white" action="" method="post">
		{% csrf_token %}
		<div class="center-block container-fluid form_data">
		
			<div class="row">
				<h2 class="border border-white bg-black">SIGN IN</h2>
			</div>
					
			<div class="row">
				<label class="label" for="id_username">Username:</label>
				{{form.username}}
			</div><br>


			<div class="row">
				<label class="label" for="id_password">Password:</label>
				{{form.password}}
			</div><br>
			
			<p class="text-danger text-center">{{result.failure}}</p>
			
			<div class="row">
				<input id="submit_login" class="text-white border border-white bg-black submit_button" type="submit" value="Login">
			</div>
		</div>
	</form>
{% endblock %}