Accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
  path('register/', views.register, name="registration"),
  path('signin/', views.sign_in, name="signin"),
  path('changepassword/', views.change_password, name="changepassword"),
  path('logout/', views.sign_off, name="logout"),
  path('account/', views.my_account, name="my_account"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FlightRadar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OpenSkyProxy.urls')),
    path('', include('Accounts.urls')),
]

OpenSkyProxy/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('planes_data/', views.planes_data, name="planesdata"),
    path('lookup/', views.lookup, name="lookup"),
    path('lookup-airplanes/', views.lookup_planes, name="planeslookup"),
    path('lookup-airports/', views.lookup_airports, name="airportslookup"),
    path('lookup-flights/', views.lookup_flights, name="flightslookup"),
    path('add/', views.add_flight, name="addflight"),
    path('route/', views.calculate_route, name="calculateroute"),
    path('responsive-form/', views.responsive_form_data, name="responsiveformdata"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

OpenSkyProxy/models.py
import uuid
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, LineString
import xml.etree.ElementTree as ET
from math import sin, cos, sqrt, atan2, radians
import json
from django.core.serializers import serialize
from datetime import timedelta
from datetime import datetime
import math

class Waypoint(models.Model):
    name = models.CharField(max_length=50, primary_key=True, unique=True, default=uuid.uuid4)
    location = models.PointField(null=True)
    adj = models.ManyToManyField("self", blank=True)

    objects = models.Manager()

    def from_xml(self, el):
        if Waypoint.objects.filter(name = el.find('name').text).exists():
            return
        else:
            self.name = el.find('name').text
            print(self.name)
            self.location = Point(float(el.attrib['lat']), float(el.attrib['lon']))
            self.save()

    def from_airports(self):
        airports = Airport.objects.all()
        for a in airports:
            w = Waypoint()
            w.name = a.name
            w.location = a.location

class Airport(models.Model):
    id = models.CharField(max_length=50, primary_key=True, unique=True, default=uuid.uuid4) #IATA code
    name = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=50, null=True)
    location = models.PointField(null=True)

    adj = models.ManyToManyField(Waypoint, blank=True)

    objects = models.Manager()

    def from_file(self, line):
        tmp = line.replace('\n', '')
        parts = tmp.split(';')
        self.name = parts[0].strip()
        self.city = parts[1].strip()
        self.country = parts[2].strip()
        self.id = parts[3].strip()
        self.location = Point(float(parts[4]), float(parts[5]))
        self.save()

    def from_json(self, json):
        self.name = json['name']
        self.city = json['city']
        self.country = json['country']
        self.id = json['id']
        self.location = Point(json['lat'], json['lng'])
        self.save()

class Plane(models.Model):
    name = models.CharField(max_length=50, primary_key=True, unique=True, default=uuid.uuid4)
    flight_range = models.FloatField(null=True)
    speed = models.FloatField(null=True)
    max_passenger = models.IntegerField(null=True)

    objects = models.Manager()

    def from_file(self, line):
        tmp = line.replace('\n', '')
        #print(line)
        parts = tmp.split(';')
        self.name = parts[0].strip()
        if 'Adamjet' in self.name:
            print(self.name)
        self.flight_range = float(parts[1].replace(' ', ''))
        self.speed = float(parts[2].replace(' ', ''))
        self.max_passenger = int(parts[3].replace(' ', ''))
        self.save()

    def from_json(self, json):
        self.name = json['name']
        self.flight_range = json['flight_range']
        self.speed = json['speed']
        self.max_passenger = json['max_passenger']
        self.save()

#Distance in km for two latlng Points
def haversine(p1, p2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(p1.x)
    lon1 = radians(p1.y)
    lat2 = radians(p2.x)
    lon2 = radians(p2.y)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

#Find a point on a line at a given distance
def cut(line, distance):
    if distance <= 0.0 or distance >= line.length:
        return line.coords[1]
    elif line.length < distance*2:
        return line.interpolate(line.length/2)
    else:
        return line.interpolate(distance)

class Flight(models.Model):
    id = models.CharField(max_length=50, primary_key=True, unique=True, default=uuid.uuid4)
    location = models.PointField(null=True)

    departure_time = models.DateTimeField(null=True)
    departure_airport = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='%(class)s_departure_airport', null=True)

    arrival_time = models.DateTimeField(null=True)
    arrival_airport = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='%(class)s_arrival_airport', null=True)
    alternate_airport = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='%(class)s_alternate_airport', null=True)

    plane = models.ForeignKey(Plane, on_delete=models.CASCADE, related_name='%(class)s_plane', null=True)
    route = models.LineStringField(null=True)

    objects = models.Manager()

    def calculate_route(self):
        #FLight range check
        base_distance = haversine(self.departure_airport.location, self.arrival_airport.location)
        alt_distance = base_distance + haversine(self.arrival_airport.location, self.alternate_airport.location)
        if base_distance * 1.1 > self.plane.flight_range:
            return {'result': 'Failure', 'reason': 'Distance between the origin and destination is bigger than the flight range!'}
        if alt_distance * 1.1 > self.plane.flight_range:
            return {'result': 'Failure', 'reason': 'Distance in case of alternative destination landing is bigger than the flight range!'}

        min_cut_distance = 5
        max_cut_distance = 10
        local_route = []
        local_route.append(self.departure_airport.location)
        waypoint_route = []
        waypoint_route.append(self.departure_airport.name)

        #Check if the route needs to be cut
        if self.departure_airport.location.distance(self.arrival_airport.location)<=max_cut_distance:
            self.route = LineString(self.departure_airport.location, self.arrival_airport.location)
            local_route.append(self.arrival_airport.location)
            list_json = [(p.x, p.y) for p in local_route]
            waypoint_route.append(self.arrival_airport.name)
            return {'result': 'Success', 'reason': 'Flight has been submitted successfully!', 'route': list_json, 'waypoints': waypoint_route}

        #Add first cut to the route
        straight_route_line = LineString(self.departure_airport.location, self.arrival_airport.location)
        next_cut = cut(straight_route_line, (max_cut_distance+min_cut_distance)/2)
        next_stop = Waypoint()
        min_distance = 100000000
        for w in self.departure_airport.adj.all():
            distance = w.location.distance(next_cut)
            if distance < min_distance:
                next_stop = w
                min_distance = distance
        local_route.append(next_stop.location)
        waypoint_route.append(next_stop.name)

        while next_stop!=self.arrival_airport:
            min_distance = 100000000
            straight_route_line = LineString(next_stop.location, self.arrival_airport.location)
            next_cut = cut(straight_route_line, (max_cut_distance + min_cut_distance) / 2)
            if next_cut == self.arrival_airport.location or next_stop.location.distance(self.arrival_airport.location)<=max_cut_distance:
                next_stop=self.arrival_airport
                local_route.append(next_stop.location)
                waypoint_route.append(next_stop.name)
            else:
                for w in next_stop.adj.all():
                    distance = w.location.distance(next_cut)
                    if distance < min_distance:
                        next_stop = w
                        min_distance = distance
                local_route.append(next_stop.location)
                waypoint_route.append(next_stop.name)
        self.route = LineString([(pt.x, pt.y) for pt in local_route])
        list_json = [(p.x, p.y) for p in local_route]
        result = {'result': 'Success', 'reason': 'Flight has been submitted successfully!', 'route': list_json, 'waypoints': waypoint_route}
        return result

    def calculate_arrival_time(self):
        distance = 0
        prev = None
        for w in self.route:
            if not prev:
                prev = w
            else:
                distance += haversine(Point(prev), Point(w))
                prev = w
        speed = self.plane.speed
        time = distance / speed # in hours
        num_hours = math.floor(time)
        num_minutes = math.floor((time-num_hours)*60)
        if isinstance(self.departure_time, str):
            departure_time = datetime.strptime(self.departure_time, '%Y-%m-%dT%H:%M:%S')
        else:
            departure_time = self.departure_time
        self.arrival_time = departure_time+timedelta(hours=num_hours, minutes=num_minutes)

    def calculate_location(self):
        if isinstance(self.departure_time, str):
            departure_time = datetime.strptime(self.departure_time, '%Y-%m-%dT%H:%M:%S')
        else:
            departure_time = self.departure_time

        if self.arrival_time<datetime.now():
            self.location = self.arrival_airport.location

        if self.departure_time > datetime.now():
            self.location = self.departure_airport.location
        else:
            cur_time = datetime.now() - departure_time
            cur_time = cur_time.total_seconds() / (60 * 60)

        cur_distance=self.plane.speed*cur_time

        prev = None
        for w in self.route:
            if not prev:
                prev = w
            else:
                if cur_distance-haversine(Point(prev), Point(w))>0:
                    cur_distance -= haversine(Point(prev), Point(w))
                    prev = w
                else:
                    straight_route_line = LineString(Point(prev), Point(w))
                    next_cut = cut(straight_route_line, cur_distance)
                    print(next_cut)
                    if isinstance(next, Point):
                        self.location = next_cut
                    else:
                        self.location = Point(next_cut)
                    break

#helper functions for loading the data
def airport_population():
    Airport.objects.all().delete()

OpenSkyProxy/forms.py
from django import forms
from .models import Plane, Airport


class AddFlightForm(forms.Form):
    airports = Airport.objects.all().order_by('name').distinct('name')
    planes = Plane.objects.all().order_by('name').distinct('name')

    airports_choices = []
    for a in airports:
        airports_choices.append((a.id, a.name))

    planes_choices = []
    for p in planes:
        planes_choices.append((p.name, p.name))

    departure_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class':'input', 'type':'datetime-local'}))
    departure_airport = forms.ChoiceField(choices=airports_choices, widget=forms.Select(attrs={'class':'input'}))
    arrival_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class':'input', 'type':'datetime-local'}))
    arrival_airport = forms.ChoiceField(choices=airports_choices, widget=forms.Select(attrs={'class':'input'}))
    alternate_airport = forms.ChoiceField(choices=airports_choices, widget=forms.Select(attrs={'class':'input'}))
    plane = forms.ChoiceField(choices=planes_choices, widget=forms.Select(attrs={'class':'input'}))

OpenSkyProxy/templates/add_flight.html
{% extends "base_auth.html" %}

{% block include %} 
{% load  static %}
<script type="text/javascript" src="{% static 'js/add-flight.js' %}"></script>
<script type="text/javascript" src="{% static 'js/onChange.js' %}"></script>
<script type="text/javascript" src="{% static 'js/default_values.js' %}"></script>
{% endblock %}

{% block content %}	
	<form id="add_flight_form" class="col-xl-9 col-sm-12 text-white border border-white"> 
		{% csrf_token %}
		<div class="center-block container-fluid form_data">
		
			<div class="row">
				<h2 class="border border-white bg-black">ADD A FLIGHT</h2>
			</div>
			
			<div class="row">
				<label class="block_label" for="dep_country">Departure country:</label>
				<select id='dep_country' class='block_input' onchange="onCountryChange(this);">
					{% for country in data.countries %}
						<option>{{ country }}</option>
					{% endfor %}
				</select>
			</div><br>
			
			<div class="row">
				<label class="block_label" for="dep_city">Departure city:</label>
				<select id='dep_city' class='block_input' onchange="onCityChange(this);">
					{% for city in data.cities %}
						<option>{{ city }}</option>
					{% endfor %}
				</select>
			</div><br>
			
			<div class="row">
				<label class="block_label" for="dep_airport">Departure airport:</label>
				<select id='dep_airport' class='block_input' onchange="onAirportChange(this);">
					{% for airport in data.airports %}
						<option>{{ airport }}</option>
					{% endfor %}
				</select>
			</div><br>
			
			<div class="row">
				<label class="block_label" for="dep_time">Departure time:</label>
				<input class="block_input" type="datetime-local" id="dep_time">
			</div>
			
			<hr>
			
			<div class="row">
				<label class="block_label" for="arr_country">Arrival country:</label>
				<select id='arr_country' class='block_input' onchange="onCountryChange(this);">
					{% for country in data.countries %}
						<option>{{ country }}</option>
					{% endfor %}
				</select>
			</div><br>
			
			<div class="row">
				<label class="block_label" for="arr_city">Arrival city:</label>
				<select id='arr_city' class='block_input' onchange="onCityChange(this);">
					{% for city in data.cities %}
						<option>{{ city }}</option>
					{% endfor %}
				</select>
			</div><br>
			
			<div class="row">
				<label class="block_label" for="arr_airport">Arrival airport:</label>
				<select id='arr_airport' class='block_input' onchange="onAirportChange(this);">
					{% for airport in data.airports %}
						<option>{{ airport }}</option>
					{% endfor %}
				</select>
			</div>		
			<hr>

			<div class="row">
				<label class="block_label" for="alt_country">Alternate country:</label>
				<select id='alt_country' class='block_input' onchange="onCountryChange(this);">
					{% for country in data.countries %}
						<option>{{ country }}</option>
					{% endfor %}
				</select>
			</div><br>
			
			<div class="row">
				<label class="block_label" for="alt_city">Alternate city:</label>
				<select id='alt_city' class='block_input' onchange="onCityChange(this);">
					{% for city in data.cities %}
						<option>{{ city }}</option>
					{% endfor %}
				</select>
			</div><br>
			
			<div class="row">
				<label class="block_label" for="alt_airport">Alternate airport:</label>
				<select id='alt_airport' class='block_input' onchange="onAirportChange(this);">
					{% for airport in data.airports %}
						<option>{{ airport }}</option>
					{% endfor %}
				</select>
			</div>
			<hr>
			
			<div class="row">
				<label class="block_label" for="plane">Airplane:</label>
				<select id='plane' class='block_input'>
					{% for plane in data.planes %}
						<option>{{ plane }}</option>
					{% endfor %}
				</select>
			</div>
			
			<div id="result" class="row">
				<br><hr>
				<p id="result_text" class="bold"></p>
				<p id="flight_id_text" class="bold"> Flight ID is <span id='flight_id'></span></p>
			</div>
			
			<br>
			<div class="row">
				<input id="submit_flight" class="text-white border border-white bg-black submit_button" type="button" value="SUBMIT FLIGHT">
			</div>
		</div>
	</form>
	
{% endblock %}

OpenSkyProxy/templates/base_auth.html
<!DOCTYPE html>
<html>
	<head>
		
		<!-- Jquery ref -->
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		
		<!-- Leaflet references -->
		<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
		integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
		crossorigin=""/>	
		<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
		integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
		crossorigin=""></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-realtime/2.2.0/leaflet-realtime.min.js" type="text/javascript"></script>
		
		<!-- Bootstrap references -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
		
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!-- JS Cookie -->		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
		
		{% load  static %}
		<!-- Internal references -->
		<link rel="stylesheet" href="{% static 'css/styles.css' %}">
		<script type="text/javascript" src="{% static 'js/auth-script.js' %}"></script>
		<script type="text/javascript">
			PLANE_IMG = "{% static 'images/plane.png' %}";
		</script>
		
		{% block include %} {% endblock %}
		<!-- Disabling link underscores -->
		<STYLE>A {text-decoration: none;} </STYLE>
		
		<!-- wRunner CSS -->
		<link rel="stylesheet" href="{% static 'css/wrunner-default-theme.css' %}">
		<!-- wRunner JS -->
		<script src="{% static 'js/wrunner-native.js' %}"></script>
		
		<!-- Leaflet SelectArea -->
		<script type="text/javascript" src="{% static 'js/Map.SelectArea.js' %}"></script>
	</head>	
	
	<body class="bg-black container-fluid">
		<br>
		<div class="row justify-content-center">
			<div id="menu" class="col-xl-3 col-sm-12">
			
				<div id="account-menu">
					<a href='/account/' id="account" class="menu-button text-white border border-white bg-black text-center">MY ACCOUNT</a>
					<div id="account-submenu">
						<a href='/changepassword/' id="change_password" class="menu-button text-dark border border-white bg-gray text-center">CHANGE PASSWORD</a>
						<a href='/logout/' id="logout" class="menu-button text-dark border border-white bg-gray text-center">LOGOUT</a>	
					</div>
				</div>
				
				<a href='/' id="monitor" class="menu-button text-white border border-white bg-black text-center">WATCH PLANES</a>
				<a href='/route/' id="route" class="menu-button text-white border border-white bg-black text-center">CALCULATE A ROUTE</a>
				<a href='/add/' id="add" class="menu-button text-white border border-white bg-black text-center">ADD A FLIGHT</a>
				
				<div id="lookup-menu">
					<a href='/lookup/' id="lookup" class="menu-button text-white border border-white bg-black text-center">LOOK UP</a>
					<div id="lookup-submenu">
						<a href='/lookup-flights/' id="lookup_flights" class="menu-button text-dark border border-white bg-gray text-center">LOOK UP FLIGHTS</a>
						<a href='/lookup-airports/' id="lookup_airports" class="menu-button text-dark border border-white bg-gray text-center">LOOK UP AIRPORTS</a>	
						<a href='/lookup-airplanes/' id="lookup_airplanes" class="menu-button text-dark border border-white bg-gray text-center">LOOK UP AIRPLANES</a>
					</div>
				</div>
				
				{% if data.account_type == 'Admin' %}
				<a href='/admin/' id="admin" class="menu-button text-white border border-white bg-black text-center">ADMIN PANEL</a>
				{% endif %}
			</div>
			
			{% block content %}	{% endblock %}
			
		</div>
		
	</body>	
</html>

OpenSkyProxy/templates/calculate_route.html
{% extends "base_auth.html" %}

{% block include %} 
{% load  static %}
<script type="text/javascript" src="{% static 'js/route-script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/default_values.js' %}"></script>
<script type="text/javascript" src="{% static 'js/onChange.js' %}"></script>
{% endblock %}

{% block content %}	
	<form id="add_flight_form" class="col text-white border border-white right-margin-15">	
		<div class="container-fluid form_data row right-padding">
		<!--  add-right-margin -->
			<div class='nested'>
				<h2 class="border border-white bg-black">FLIGHT PARAMETERS</h2>
			</div>
			<div class="row right-padding">
				<div class='col'>
					<div class="row">
						<label class="block_label" for="dep_country">Departure country:</label>
						<select id='dep_country' class='block_input' onchange="onCountryChange(this);">
							{% for country in data.countries %}
								<option>{{ country }}</option>
							{% endfor %}
						</select>
					</div><br>
					
					<div class="row">
						<label class="block_label" for="dep_city">Departure city:</label>
						<select id='dep_city' class='block_input' onchange="onCityChange(this);">
							{% for city in data.cities %}
								<option>{{ city }}</option>
							{% endfor %}
						</select>
					</div><br>
					
					<div class="row">
						<label class="block_label" for="dep_airport">Departure airport:</label>
						<select id='dep_airport' class='block_input' onchange="onAirportChange(this);">
							{% for airport in data.airports %}
								<option>{{ airport }}</option>
							{% endfor %}
						</select>
					</div><br>
				</div>
				
				<div class='col'>
					<div class="row">
						<label class="block_label" for="arr_country">Arrival country:</label>
						<select id='arr_country' class='block_input' onchange="onCountryChange(this);">
							{% for country in data.countries %}
								<option>{{ country }}</option>
							{% endfor %}
						</select>
					</div><br>
					
					<div class="row">
						<label class="block_label" for="arr_city">Arrival city:</label>
						<select id='arr_city' class='block_input' onchange="onCityChange(this);">
							{% for city in data.cities %}
								<option>{{ city }}</option>
							{% endfor %}
						</select>
					</div><br>
					
					<div class="row">
						<label class="block_label" for="arr_airport">Arrival airport:</label>
						<select id='arr_airport' class='block_input' onchange="onAirportChange(this);">
							{% for airport in data.airports %}
								<option>{{ airport }}</option>
							{% endfor %}
						</select>
					</div><br>
				</div>

				<div class='col'>
					<div class="row">
						<label class="block_label" for="alt_country">Alternate country:</label>
						<select id='alt_country' class='block_input' onchange="onCountryChange(this);">
							{% for country in data.countries %}
								<option>{{ country }}</option>
							{% endfor %}
						</select>
					</div><br>
					
					<div class="row">
						<label class="block_label" for="alt_city">Alternate city:</label>
						<select id='alt_city' class='block_input' onchange="onCityChange(this);">
							{% for city in data.cities %}
								<option>{{ city }}</option>
							{% endfor %}
						</select>
					</div><br>
					
					<div class="row">
						<label class="block_label" for="alt_airport">Alternate airport:</label>
						<select id='alt_airport' class='block_input' onchange="onAirportChange(this);">
							{% for airport in data.airports %}
								<option>{{ airport }}</option>
							{% endfor %}
						</select>
					</div><br>
				</div>
			</div>
			
			
			<div class='row right-padding'>
				<div class="col-xl-4">
					<div class="row">
						<label class="block_label" for="plane">Airplane:</label>
						<select id='plane' class='block_input'>
							{% for plane in data.planes %}
								<option>{{ plane }}</option>
							{% endfor %}
						</select><br>
					</div>
				</div>
				
				<div class="col-xl-4">
					<div class="row">
						<label class="block_label" for="dep_time">Departure time:</label>
						<input class="block_input" type="datetime-local" id="dep_time" required="true" />
					</div><br>
				</div>
		
			</div>

			
			<div id="result" class="row text-center">
				<br><hr>
				<p id="result_text" class="bold"></p>
			</div>
			
			<div class='nested'>
				<input id="calculate_route" class="text-white border border-white bg-black submit_button" type="button" value="CALCULATE">
			</div>
			
			<div id='route_map' class=''></div>
		</div>
		
		<div id="display_route_form" class="container-fluid form_data row">
			<table id="display_route_table" class="table text-white border border-white">
			</table>
		</div>
		
	</form>
	

{% endblock %}

OpenSkyProxy/templates/lookup_airplanes.html
{% extends "base_auth.html" %}

{% block include %} 
{% load  static %}
<script type="text/javascript" src="{% static 'js/airplanes-script.js' %}"></script>
{% endblock %}

{% block content %}	
	<form id="lookup_airplanes_form" class="col-xl-9 col-sm-12 text-white border border-white"> 
		{% csrf_token %}
		<div class="container-fluid form_data row right-padding align-text-bottom">
		
			<div class="nested">
				<h2 class="border border-white bg-black">LOOK UP AIRPLANES</h2>
			</div>
			
			<div class="row">
				<label class="label" for="name">Name:</label>
				<input class="input" type="text" id="name">
			</div><br>

			<div class="row d-flex">
				<label class="label align-self-center" for="id_flight_range">Flight range:</label>
				<div id='flight_range_slider' class='input'></div>
			</div><br>
			
			<div class="row d-flex">
				<label class="label align-self-center" for="id_speed_range">Cruise speed:</label>
				<div id='speed_range_slider' class='input'></div>
				<!-- {{form.speed_range}} -->
			</div><br>

			<div class="row d-flex">
				<label class="label align-self-center" for="id_max_passenger">Maximum number of passengers:</label>
				<div id='max_passenger_slider' class='input'></div><br>
			</div><br><br>
			
			<div class="nested">
				<input id="submit_lookup_airplanes" class="text-white border border-white bg-black submit_button" type="button" value="Search">
			</div>
			
			
			<div id="display_airplanes_form" class="nested">
				<table id="display_airplanes_table" class="table text-white border border-white">
				</table>
			</div>
		</div>
	</form>

	<!-- Setting the sliders -->
	<script>  	
		var flight_range_setting = {
			roots: document.querySelector('#flight_range_slider'),
			type: 'range',
			step: 1,
			limits : { minLimit: {{data.min_flight_range.flight_range__min}}, 
						maxLimit: {{data.max_flight_range.flight_range__max}}  },
			rangeValue : { minValue: {{data.min_flight_range.flight_range__min}}, 
						maxValue: {{data.max_flight_range.flight_range__max}}  },		
		}
		var flight_range_slider = wRunner(flight_range_setting);
		
		var speed_range_setting = {
			roots: document.querySelector('#speed_range_slider'),
			type: 'range',
			step: 1,
			limits : { minLimit: {{data.min_speed_range.speed__min}}, 
						maxLimit: {{data.max_speed_range.speed__max}}  },
			rangeValue : { minValue: {{data.min_speed_range.speed__min}}, 
						maxValue: {{data.max_speed_range.speed__max}}  },
		}
		var speed_range_slider = wRunner(speed_range_setting);
		
		var max_passenger_setting = {
			roots: document.querySelector('#max_passenger_slider'),
			type: 'range',
			step: 1,
			limits : { minLimit: {{data.max_passenger_min.max_passenger__min}}, 
						maxLimit: {{data.max_passenger_max.max_passenger__max}}  },
			rangeValue: { minValue: {{data.max_passenger_min.max_passenger__min}}, 
						maxValue: {{data.max_passenger_max.max_passenger__max}}  },
		}
		var max_passenger_slider = wRunner(max_passenger_setting);
	</script>

{% endblock %}